name: Build Web Application

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build the Web Application
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Install npm dependencies
      run: npm install

    - name: Compile Sass assets
      run: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'

    - name: Run Gulp tasks
      run: npx gulp

    - name: Write build info
      run: echo "${{ github.workflow }}, ${{ github.run_id }}, ${{ github.run_number }}" > Tailspin.SpaceGame.Web/wwwroot/buildinfo.txt

    - name: Restore project dependencies
      run: dotnet restore "**/*.csproj"

    - name: Build the project
      run: dotnet build "**/*.csproj" --no-restore --configuration Release

    - name: Publish the project
      run: |
        dotnet publish "**/*.csproj" \
          --no-build \
          --configuration Release \
          --output ${{ github.workspace }}/artifacts/Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: drop
        path: ${{ github.workspace }}/artifacts/Release
